### ISSUE TITLE
Could not use the CLI instructions

### ISSUE THREAD

**Issue by maelvls** [unleash-hosted/unleash-hosted-gcp-marketplace#2]
Hi,

While trying to follow the CLI instructions as shown on the screenshot:

   <img width="500" alt="unleash-cli-installation-in-the-marketplace-ui" src="https://user-images.githubusercontent.com/2195781/108189170-bda42a00-7110-11eb-9bac-7097dfce1193.png">

I did download the license file `license.yaml` and applied it:

```sh
kubectl apply -f license.yaml
```

I did the steps detailed in the readme at https://github.com/unleash-hosted/unleash-hosted-gcp-marketplace, but I ended up having the error:

```sh
% helm template "$APP_INSTANCE_NAME" chart/unleash-enterprise \
  --namespace "$NAMESPACE" \
  --set unleash.image.repo="$IMAGE_UNLEASH" \
  --set unleash.image.tag="$TAG" \
  --set postgresql.image="$IMAGE_POSTGRESQL" \
  --set postgresql.db.password="$POSTGRESQL_DB_PASSWORD" \
  --set metrics.image="$IMAGE_METRICS_EXPORTER" \
  --set metrics.exporter.enabled="$METRICS_EXPORTER_ENABLED" \
  > "${APP_INSTANCE_NAME}_manifest.yaml"

% kubectl apply -n $NAMESPACE -f unleash-1_manifest.yaml
serviceaccount/unleash-1-serviceaccount created
secret/unleash-1-secret created
configmap/ubbagent-config created
Warning: Detected changes to resource unleash-1-postgresql-pvc which is currently being deleted.
persistentvolumeclaim/unleash-1-postgresql-pvc created
service/unleash-1-postgresql-service created
service/unleash-1-unleash-enterprise-svc created
statefulset.apps/unleash-1-postgresql created
application.app.k8s.io/unleash-1 created
The Deployment "unleash-1-unleash-enterprise" is invalid:
* spec.template.spec.containers[1].env[2].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
* spec.template.spec.containers[1].env[3].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Three questions:
- How can I go around this issue?
- Why is the `kubectl apply -f license.yaml` not using my namespace? Shouldn't it have the `-n $NAMESPACE` flag?
- I tried to open the [link](https://www.unleash-hosted.com/google-cloud-marketplace) in step (4) in the screenshot, but it seems to point to some UI instructions and is unhelpful for using the CLI; should I follow [the README](https://github.com/unleash-hosted/unleash-hosted-gcp-marketplace) instead?

**Comment by ivarconr** [comment]
Hi, if you are installing from CLI your best bet is to follow the readme in this project. 

My first impression from the error is that you forgot to generate the password and thus $POSTGRESQL_DB_PASSWORD is empty. 

can you verify that you have generated a password for postgres?

**Comment by ivarconr** [comment]
So we did test the instructions, and found that there was a mission step on how to provide the license secret. We updated the readme to fully reflect what you need to do. Thanks for reporting this @maelvls
